name: Run Robin Automation

on:
  workflow_dispatch:
    inputs:
      proposal_id:
        description: 'Proposal ID'
        required: true
      page_id:
        description: 'Page ID'
        required: true
      callback_url:
        description: 'Webhook URL'
        required: true

jobs:
  automation:
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.42.0-focal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run Robin Automation
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          export PROPOSAL_ID=${{ github.event.inputs.proposal_id }}
          export PAGE_ID=${{ github.event.inputs.page_id }}
          export CALLBACK_URL=${{ github.event.inputs.callback_url }}
          python3 main.py